### ISSUE TITLE
Flashing is hard to initiate with prog mapped to record

### ISSUE THREAD

**Issue by tremby** [cdisselkoen/Kaleidoscope-MacrosOnTheFly#6]
With prog mapped to record, it's hard to re-flash, for which I need to hold prog and press enter, since doing so starts to record to the enter key, without actually sending enter!

I have to type prog, then any slot, then hold prog (which stops recording and flashes the keys green) and press enter.

I wonder whether anything can be done about this.

**Comment by cdisselkoen** [comment]
Alternately, hold prog, press enter to select the enter slot, then press enter again and it will go through.  (You've recorded an "enter" keypress to the enter slot - but when you're flashing all your macros will be cleared anyway.)

This is another one of those cases that is a fundamental fact about mapping things to the `prog` key - Kaleidoscope will always act on the `prog` keypress when you press it, because that's what you told it to do.  I'm not sure whether we can do something special to address this situation in particular, but I'll think about it.

**Comment by cdisselkoen** [comment]
One general workaround (works for any key mapped to `prog`, not just `Key_MacroRec`) was suggested by @algernon - namely, you could use [Kaleidoscope-TapDance](https://github.com/keyboardio/Kaleidoscope-TapDance) to make double-tapping `prog` be `Key_NoKey`.  Then to flash, just double tap and hold the second tap - no `Key_MacroRec` will ever be sent.

That's not a specific solution for this case, but I'd say it would qualify as a recommended solution to these kinds of issues.

**Comment by tremby** [comment]
That definitely seems like a decent solution.

**Comment by algernon** [comment]
The major issue with having `Prog` a TapDance key is that I **always** forget to double-tap it.

I was thinking about doing it a different way, like sending the reset code twice, the first time to let the keyboard know to disable the key. Or using a Focus hook, and sending a command prior to flashing. Something I can automate and don't have to remember.

**Comment by cdisselkoen** [comment]
I'm going to consider this issue closed unless someone objects.

@algernon's suggestions are great, but outside the scope of this MacrosOnTheFly issue (and rightly so, as they would apply to all firmwares).
